### ISSUE TITLE
add sentfiles to initial-files on uploaded

### ISSUE THREAD

**Issue by devJoshLopez** [InCuca/ic-firebase-uploader#4]
Please forgive my newbie brain. Your help with the initial-files helped out a lot. Now I have the files showing up when i view the uploader. What I cant figure out now is how to add the files that are uploaded to the initial-files object. Any suggestions? 

What I have is an object like this that im uploading to firebase. Im trying to put the files uploaded into resources: [] 

```
[
        {
          key: "5mjyfa4",
          title: "Module Title mnn31hf",
          expanded: true,
          isModule: true,
          nested: [
            {
              key: "wuy6zz3",
              title: "Lesson Title kkr55x2",
              description:
                "<p>lorem ipsum sadkfjhn sldkfhlkjsdhn fljnsdjknflkjsdnfkjlnsd jsdjknflkjsdn flkjsdn l</p>",
              resources: [{file1: 'path/to/the/image1, file2: 'path/to/the/image2’}],
              videoEmbedCode: "",
              expanded: true,
              isLesson: true
            },
            {
              key: "z31sgu5",
              title: "Lesson Title t2s696v",
              description:
                "<p>lorem ipsum sadkfjhn sldkfhlkjsdhn fljnsdjknflkjsdnfkjlnsd jsdjknflkjsdn flkjsdn l</p>",
              resources: [],
              videoEmbedCode: "",
              expanded: false,
              isLesson: true
            }
          ]
        },
        {
          key: "lecxccv",
          title: "Module Title u4ud20k",
          expanded: false,
          isModule: true,
          nested: [
            {
              key: "z385lgz",
              title: "Lesson Title iv6bdkn",
              description:
                "<p>lorem ipsum sadkfjhn sldkfhlkjsdhn fljnsdjknflkjsdnfkjlnsd jsdjknflkjsdn flkjsdn l</p>",
              resources: []},
              videoEmbedCode: "",
              expanded: false,
              isLesson: true
            }
          ]
        }
      ];
```

my template code looks like 

```
                        <IcFirebaseUploader
                          path="lesson-files"
                          max-files="6"
                          :getFileName="getFileName"
                          :storage="getStorage()"
                          :initial-files="item.resources"
                          @upload="onUpload"
                          @uploaded="onUploaded"
                          @delete="onDelete"
                          @deleted="onDeleted"
                          @click="onClick"
                          @error="onError"
                        />
```
the initial-files is item.resources because everything is in a v-for

**Comment by klarkc** [comment]
Let me know if I understand correctly, are you trying to save file in item.resources for future usage? If that's true, first you should have saved file ID AND file path in items.resources object using uploaded event. (Please note that [changing deep object values directly in Vue does not trigger component re-renders](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats))

Then:

As you can see here:

https://github.com/InCuca/ic-firebase-uploader/blob/4849224079a7297e06dc163456f0360519005940/src/ic-firebase-uploader/ic-firebase-uploader.vue#L85

`initialFiles` expect an object containing key-value pairs (probably because it's easier to match firebase format).

So you need to transform your actual `item.resources` array to something like that. Eg:

```html
:initial-files="toKeyValueObj(item.resources, 'fileId', 'filePath')"
```

```js
toKeyValueObj(resources, fileId, filePath) {
    return resources.reduce((prev, next) => ({...prev, [next[fileId]]: next[filePath]}), {})
}
```
`fileId` is the key containing firebase file ID of your resources objects.
`filePath` is the key containing firebase file path of your resources objets.
